import numpy as np
arr = np.array([2147483647])
print(arr,arr.dtype)
arr = np.array([2147483648])
print(arr,arr.dtype)
arr = np.array(["S","A","B"])
print(arr,arr.dtype)
arr = np.array([1,2,3,4,5],dtype='U')
print(arr,arr.dtype)
arr = np.array([1.1,'a'])
print(arr,arr.dtype)
arr = np.array([1.1,1.6,2.1])
print(arr,arr.dtype)
narr = arr.astype('i4')
print(narr,narr.dtype)
arr = np.array([1,2,0,1,0])
print(arr,arr.dtype)
narr = arr.astype(bool)
print(narr,narr.dtype)
